const emojis={  "2049": ["interrobang"],
                "2122": ["tm"],
                "2139": ["information source"],
                "2194": ["left right arrow"],
                "2195": ["arrow up down"],
                "2196": ["arrow upper left"],
                "2197": ["arrow upper right"],
                "2198": ["arrow lower right"],
                "2199": ["arrow lower left"],
                "2328": ["keyboard"],
                "2600": ["sunny"],
                "2601": ["cloud"],
                "2602": ["umbrella"],
                "2603": ["showman"],
                "2604": ["comet"],
                "2611": ["ballot box with check"],
                "2614": ["umbrella"],
                "2615": ["coffee"],
                "2618": ["shamrock"],
                "2620": ["skull and crossbones"],
                "2622": ["radioactive sign"],
                "2623": ["biohazard sign"],
                "2626": ["orthodox cross"],
                "2638": ["wheel of dharma"],
                "2639": ["white frowning face"],
                "2648": ["aries"],
                "2649": ["taurus"],
                "2650": ["sagittarius"],
                "2651": ["capricorn"],
                "2652": ["aquarius"],
                "2653": ["pisces"],
                "2660": ["spades"],
                "2663": ["clubs"],
                "2665": ["hearts"],
                "2666": ["diamonds"],
                "2668": ["hotsprings"],
                "2692": ["hammer and pick"],
                "2693": ["anchor"],
                "2694": ["crossed swords"],
                "2696": ["scales"],
                "2697": ["alembic"],
                "2699": ["gear"],
                "2702": ["scissors"],
                "2705": ["white check mark"],
                "2708": ["airplane"],
                "2709": ["email","envelope"],
                "2712": ["black nib"],
                "2714": ["heavy check mark"],
                "2716": ["heavy multiplication x"],
                "2721": ["star of david"],
                "2728": ["sparkles"],
                "2733": ["eight spoked asterisk"],
                "2734": ["eight pointed black star"],
                "2744": ["snowflake"],
                "2747": ["sparkle"],
                "2753": ["question"],
                "2754": ["grey question"],
                "2755": ["grey exclamation"],
                "2757": ["exclamation","heavy exclamation mark"],
                "2763": ["heavy heart exclamation mark ornament"],
                "2764": ["heart"],
                "2795": ["heavy plus sign"],
                "2796": ["heavy minus sign"],
                "2797": ["heavy division sign"],
                "2934": ["arrow heading up"],
                "2935": ["arrow heading down"],
                "3030": ["wavy dash"],
                "3297": ["congratulations"],
                "3299": ["secret"],
                "00a9": ["copyright"],
                "00ae": ["registered"],
                "203c": ["bangbang"],
                "21a9": ["leftwards arrow with hook"],
                "21aa": ["arrow right hook"],
                "231a": ["watch"],
                "231b": ["hourglass"],
                "23e9": ["fast forward"],
                "23ea": ["rewind"],
                "23eb": ["arrow double up"],
                "23ec": ["arrow double down"],
                "23ed": ["black right pointing double triangle with vertical bar"],
                "23ee": ["black left pointing double triangle with vertical bar"],
                "23ef": ["black right pointing triangle with double vertical bar"],
                "23f0": ["alarm clock"],
                "23f1": ["stopwatch"],
                "23f2": ["timer clock"],
                "23f3": ["hourglass flowing sand"],
                "23f8": ["double vertical bar"],
                "23f9": ["black square for stop"],
                "23fa": ["black circle for record"],
                "24c2": ["m"],
                "25aa": ["black small square"],
                "25ab": ["white small square"],
                "25b6": ["arrow forward"],
                "25c0": ["arrow backward"],
                "25fb": ["white medium square"],
                "25fc": ["black medium square"],
                "25fd": ["white medium small square"],
                "25fe": ["black medium small square"],
                "260e": ["phone","telephone"],
                "261d": ["point up"],
                "262a": ["star and crescent"],
                "262e": ["peace symbol"],
                "262f": ["yin yang"],
                "263a": ["relaxed"],
                "264a": ["gemini"],
                "264b": ["cancer"],
                "264c": ["leo"],
                "264d": ["virgo"],
                "264e": ["libra"],
                "264f": ["scorpius"],
                "267b": ["recycle"],
                "267f": ["wheelchair"],
                "269b": ["atom symbol"],
                "269c": ["fleur de lis"],
                "26a0": ["warning"],
                "26a1": ["zap"],
                "26aa": ["white circle"],
                "26ab": ["black circle"],
                "26b0": ["coffin"],
                "26b1": ["funeral urn"],
                "26bd": ["soccer"],
                "26be": ["baseball"],
                "26c4": ["snowman"],
                "26c5": ["partly sunny"],
                "26c8": ["thunder cloud and rain"],
                "26ce": ["ophiuchus"],
                "26cf": ["pick"],
                "26d1": ["helmet with white cross"],
                "26d3": ["chains"],
                "26d4": ["no entry"],
                "26e9": ["shinto shrine"],
                "26ea": ["church"],
                "26f0": ["mountain"],
                "26f1": ["umbrella on ground"],
                "26f2": ["fountain"],
                "26f3": ["golf"],
                "26f4": ["ferry"],
                "26f5": ["boat","sailboat"],
                "26f7": ["skier"],
                "26f8": ["ice skate"],
                "26f9": ["person with ball"],
                "26fa": ["tent"],
                "26fd": ["fuelpump"],
                "270a": ["fist"],
                "270b": ["hand","raised hand"],
                "270c": ["v"],
                "270d": ["writing hand"],
                "270f": ["pencil2"],
                "271d": ["latin cross"],
                "274c": ["x"],
                "274e": ["negative squared cross mark"],
                "27a1": ["arrow right"],
                "27b0": ["curly loop"],
                "27bf": ["loop"],
                "2b05": ["arrow left"],
                "2b06": ["arrow up"],
                "2b07": ["arrow down"],
                "2b1b": ["black large square"],
                "2b1c": ["white large square"],
                "2b50": ["star"],
                "2b55": ["o"],
                "303d": ["part alternation mark"],
                "1f004": ["mahjong"],
                "1f0cf": ["black joker"],
                "1f170": ["a"],
                "1f171": ["b"],
                "1f17e": ["o2"],
                "1f17f": ["parking"],
                "1f18e": ["ab"],
                "1f191": ["cl"],
                "1f192": ["cool"],
                "1f193": ["free"],
                "1f194": ["id"],
                "1f195": ["new"],
                "1f196": ["ng"],
                "1f197": ["ok"],
                "1f198": ["sos"],
                "1f199": ["up"],
                "1f19a": ["vs"],
                "1f201": ["koko"],
                "1f202": ["sa"],
                "1f21a": ["chinese character"],
                "1f22f": ["chinese character"],
                "1f232": ["chinese character"],
                "1f233": ["chinese character"],
                "1f234": ["chinese character"],
                "1f235": ["chinese character"],
                "1f236": ["chinese character"],
                "1f237": ["chinese character"],
                "1f238": ["chinese character"],
                "1f239": ["chinese character"],
                "1f23a": ["chinese character"],
                "1f250": ["ideograph advantage"],
                "1f251": ["accept"],
                "1f300": ["cyclone"],
                "1f301": ["foggy"],
                "1f302": ["closed umbrella"],
                "1f303": ["night with stars"],
                "1f304": ["sunrise over mountains"],
                "1f305": ["sunrise"],
                "1f306": ["city sunset"],
                "1f307": ["city sunrise"],
                "1f308": ["rainbow"],
                "1f309": ["bridge at night"],
                "1f30a": ["ocean"],
                "1f30b": ["volcano"],
                "1f30c": ["milky way"],
                "1f30d": ["earth africa"],
                "1f30e": ["earth americas"],
                "1f30f": ["earth asia"],
                "1f310": ["globe with meridians"],
                "1f311": ["new moon"],
                "1f312": ["waxing crescent moon"],
                "1f313": ["first quarter moon"],
                "1f314": ["moon","waxing gibbous moon"],
                "1f315": ["full moon"],
                "1f316": ["waning gibbous moon"],
                "1f317": ["last quarter moon"],
                "1f318": ["waning crescent moon"],
                "1f319": ["crescent moon"],
                "1f31a": ["new moon with face"],
                "1f31b": ["first quarter moon with face"],
                "1f31c": ["last quarter moon with face"],
                "1f31d": ["full moon with face"],
                "1f31e": ["sun with face"],
                "1f31f": ["star2"],
                "1f320": ["stars"],
                "1f321": ["thermometer"],
                "1f324": ["mostly sunny","sun small cloud"],
                "1f325": ["barely sunny","sun behind cloud"],
                "1f326": ["partly sunny rain","sun behind rain cloud"],
                "1f327": ["rain cloud"],
                "1f328": ["snow cloud"],
                "1f329": ["lightning","lightning cloud"],
                "1f32a": ["tornado","tornado cloud"],
                "1f32b": ["fog"],
                "1f32c": ["wind blowing face"],
                "1f32d": ["hotdog"],
                "1f32e": ["taco"],
                "1f32f": ["burrito"],
                "1f330": ["chestnut"],
                "1f331": ["seedling"],
                "1f332": ["evergreen tree"],
                "1f333": ["deciduous tree"],
                "1f334": ["palm tree"],
                "1f335": ["cactus"],
                "1f336": ["hot pepper"],
                "1f337": ["tulip"],
                "1f338": ["cherry blossom"],
                "1f339": ["rose"],
                "1f33a": ["hibiscus"],
                "1f33b": ["sunflower"],
                "1f33c": ["blossom"],
                "1f33d": ["corn"],
                "1f33e": ["ear of rice"],
                "1f33f": ["herb"],
                "1f340": ["four leaf clover"],
                "1f341": ["maple leaf"],
                "1f342": ["fallen leaf"],
                "1f343": ["leaves"],
                "1f344": ["mushroom"],
                "1f345": ["tomato"],
                "1f346": ["eggplant"],
                "1f347": ["grapes"],
                "1f348": ["melon"],
                "1f349": ["watermelon"],
                "1f34a": ["tangerine"],
                "1f34b": ["lemon"],
                "1f34c": ["banana"],
                "1f34d": ["pineapple"],
                "1f34e": ["apple"],
                "1f34f": ["green apple"],
                "1f350": ["pear"],
                "1f351": ["peach"],
                "1f352": ["cherries"],
                "1f353": ["strawberry"],
                "1f354": ["hamburger"],
                "1f355": ["pizza"],
                "1f356": ["meat on bone"],
                "1f357": ["poultry leg"],
                "1f358": ["rice cracker"],
                "1f359": ["rice ball"],
                "1f35a": ["rice"],
                "1f35b": ["curry"],
                "1f35c": ["ramen"],
                "1f35d": ["spaghetti"],
                "1f35e": ["bread"],
                "1f35f": ["fries"],
                "1f360": ["sweet potato"],
                "1f361": ["dango"],
                "1f362": ["oden"],
                "1f363": ["sushi"],
                "1f364": ["fried shrimp"],
                "1f365": ["fish cake"],
                "1f366": ["icecream"],
                "1f367": ["shaved ice"],
                "1f368": ["ice cream"],
                "1f369": ["doughnut"],
                "1f36a": ["cookie"],
                "1f36b": ["chocolate bar"],
                "1f36c": ["candy"],
                "1f36d": ["lollipop"],
                "1f36e": ["custard"],
                "1f36f": ["honey pot"],
                "1f370": ["cake"],
                "1f371": ["bento"],
                "1f372": ["stew"],
                "1f373": ["egg"],
                "1f374": ["fork and knife"],
                "1f375": ["tea"],
                "1f376": ["sake"],
                "1f377": ["wine glass"],
                "1f378": ["cocktail"],
                "1f379": ["tropical drink"],
                "1f37a": ["beer"],
                "1f37b": ["beers"],
                "1f37c": ["baby bottle"],
                "1f37d": ["knife fork plate"],
                "1f37e": ["champagne"],
                "1f37f": ["popcorn"],
                "1f380": ["ribbon"],
                "1f381": ["gift"],
                "1f382": ["birthday"],
                "1f383": ["jack o lantern"],
                "1f384": ["christmas tree"],
                "1f385": ["santa"],
                "1f386": ["fireworks"],
                "1f387": ["sparkler"],
                "1f388": ["balloon"],
                "1f389": ["tada"],
                "1f38a": ["confetti ball"],
                "1f38b": ["tanabata tree"],
                "1f38c": ["crossed flags"],
                "1f38d": ["bamboo"],
                "1f38e": ["dolls"],
                "1f38f": ["flags"],
                "1f390": ["wind chime"],
                "1f391": ["rice scene"],
                "1f392": ["school satchel"],
                "1f393": ["mortar board"],
                "1f396": ["medal"],
                "1f397": ["reminder ribbon"],
                "1f399": ["studio microphone"],
                "1f39a": ["level slider"],
                "1f39b": ["control knobs"],
                "1f39e": ["film frames"],
                "1f39f": ["admission tickets"],
                "1f3a0": ["carousel horse"],
                "1f3a1": ["ferris wheel"],
                "1f3a2": ["roller coaster"],
                "1f3a3": ["fishing pole and fish"],
                "1f3a4": ["microphone"],
                "1f3a5": ["movie camera"],
                "1f3a6": ["cinema"],
                "1f3a7": ["headphones"],
                "1f3a8": ["art"],
                "1f3a9": ["tophat"],
                "1f3aa": ["circus tent"],
                "1f3ab": ["ticket"],
                "1f3ac": ["clapper"],
                "1f3ad": ["performing arts"],
                "1f3ae": ["video game"],
                "1f3af": ["dart"],
                "1f3b0": ["slot machine"],
                "1f3b1": ["8ball"],
                "1f3b2": ["game die"],
                "1f3b3": ["bowling"],
                "1f3b4": ["flower playing cards"],
                "1f3b5": ["musical note"],
                "1f3b6": ["notes"],
                "1f3b7": ["saxophone"],
                "1f3b8": ["guitar"],
                "1f3b9": ["musical keyboard"],
                "1f3ba": ["trumpet"],
                "1f3bb": ["violin"],
                "1f3bc": ["musical score"],
                "1f3bd": ["running shirt with sash"],
                "1f3be": ["tennis"],
                "1f3bf": ["ski"],
                "1f3c0": ["basketball"],
                "1f3c1": ["checkered flag"],
                "1f3c2": ["snowboarder"],
                "1f3c3": ["runner","running"],
                "1f3c4": ["surfer"],
                "1f3c5": ["sports medal"],
                "1f3c6": ["trophy"],
                "1f3c7": ["horse racing"],
                "1f3c8": ["football"],
                "1f3c9": ["rugby football"],
                "1f3ca": ["swimmer"],
                "1f3cb": ["weight lifter"],
                "1f3cc": ["golfer"],
                "1f3cd": ["racing motorcycle"],
                "1f3ce": ["racing car"],
                "1f3cf": ["cricket bat and ball"],
                "1f3d0": ["volleyball"],
                "1f3d1": ["field hockey stick and ball"],
                "1f3d2": ["ice hockey stick and puck"],
                "1f3d3": ["table tennis paddle and ball"],
                "1f3d4": ["snow capped mountain"],
                "1f3d5": ["camping"],
                "1f3d6": ["beach with umbrella"],
                "1f3d7": ["building construction"],
                "1f3d8": ["house buildings"],
                "1f3d9": ["cityscape"],
                "1f3da": ["derelict house building"],
                "1f3db": ["classical building"],
                "1f3dc": ["desert"],
                "1f3dd": ["desert island"],
                "1f3de": ["national park"],
                "1f3df": ["stadium"],
                "1f3e0": ["house"],
                "1f3e1": ["house with garden"],
                "1f3e2": ["office"],
                "1f3e3": ["post office"],
                "1f3e4": ["european post office"],
                "1f3e5": ["hospital"],
                "1f3e6": ["bank"],
                "1f3e7": ["atm"],
                "1f3e8": ["hotel"],
                "1f3e9": ["love hotel"],
                "1f3ea": ["convenience store"],
                "1f3eb": ["school"],
                "1f3ec": ["department store"],
                "1f3ed": ["factory"],
                "1f3ee": ["izakaya lantern","lantern"],
                "1f3ef": ["japanese castle"],
                "1f3f0": ["european castle"],
                "1f3f3": ["waving white flag"],
                "1f3f4": ["waving black flag"],
                "1f3f5": ["rosette"],
                "1f3f7": ["label"],
                "1f3f8": ["badminton racquet and shuttlecock"],
                "1f3f9": ["bow and arrow"],
                "1f3fa": ["amphora"],
                "1f3fb": ["skin-tone-2"],
                "1f3fc": ["skin-tone-3"],
                "1f3fd": ["skin-tone-4"],
                "1f3fe": ["skin-tone-5"],
                "1f3ff": ["skin-tone-6"],
                "1f400": ["rat"],
                "1f401": ["mouse2"],
                "1f402": ["ox"],
                "1f403": ["water buffalo"],
                "1f404": ["cow2"],
                "1f405": ["tiger2"],
                "1f406": ["leopard"],
                "1f407": ["rabbit2"],
                "1f408": ["cat2"],
                "1f409": ["dragon"],
                "1f40a": ["crocodile"],
                "1f40b": ["whale2"],
                "1f40c": ["snail"],
                "1f40d": ["snake"],
                "1f40e": ["racehorse"],
                "1f40f": ["ram"],
                "1f410": ["goat"],
                "1f411": ["sheep"],
                "1f412": ["monkey"],
                "1f413": ["rooster"],
                "1f414": ["chicken"],
                "1f415": ["dog2"],
                "1f416": ["pig2"],
                "1f417": ["boar"],
                "1f418": ["elephant"],
                "1f419": ["octopus"],
                "1f41a": ["shell"],
                "1f41b": ["bug"],
                "1f41c": ["ant"],
                "1f41d": ["bee","honeybee"],
                "1f41e": ["beetle"],
                "1f41f": ["fish"],
                "1f420": ["tropical fish"],
                "1f421": ["blowfish"],
                "1f422": ["turtle"],
                "1f423": ["hatching chick"],
                "1f424": ["baby chick"],
                "1f425": ["hatched chick"],
                "1f426": ["bird"],
                "1f427": ["penguin"],
                "1f428": ["koala"],
                "1f429": ["poodle"],
                "1f42a": ["dromedary camel"],
                "1f42b": ["camel"],
                "1f42c": ["dolphin","flipper"],
                "1f42d": ["mouse"],
                "1f42e": ["cow"],
                "1f42f": ["tiger"],
                "1f430": ["rabbit"],
                "1f431": ["cat"],
                "1f432": ["dragon face"],
                "1f433": ["whale"],
                "1f434": ["horse"],
                "1f435": ["monkey face"],
                "1f436": ["dog"],
                "1f437": ["pig"],
                "1f438": ["frog"],
                "1f439": ["hamster"],
                "1f43a": ["wolf"],
                "1f43b": ["bear"],
                "1f43c": ["panda face"],
                "1f43d": ["pig nose"],
                "1f43e": ["feet","paw prints"],
                "1f43f": ["chipmunk"],
                "1f440": ["eyes"],
                "1f441": ["eye"],
                "1f442": ["ear"],
                "1f443": ["nose"],
                "1f444": ["lips"],
                "1f445": ["tongue"],
                "1f446": ["point up 2"],
                "1f447": ["point down"],
                "1f448": ["point left"],
                "1f449": ["point right"],
                "1f44a": ["facepunch","punch"],
                "1f44b": ["wave"],
                "1f44c": ["ok hand"],
                "1f44d": ["+1","thumbsup"],
                "1f44e": ["-1","thumbsdown"],
                "1f44f": ["clap"],
                "1f450": ["open hands"],
                "1f451": ["crown"],
                "1f452": ["womans hat"],
                "1f453": ["eyeglasses"],
                "1f454": ["necktie"],
                "1f455": ["shirt","tshirt"],
                "1f456": ["jeans"],
                "1f457": ["dress"],
                "1f458": ["kimono"],
                "1f459": ["bikini"]
                }
